const dotenv = require("dotenv");

// 导入环境变量
dotenv.config();

const {
  APP_HOST,
  APP_PORT,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USER_NAME,
  MYSQL_PASSWORD,
  MYSQL_DATABASE,
  TENCENTCLOUD_SECRETID,
  TENCENTCLOUD_SECRETKEY,
  TENCENTCLOUD_SESSIONTOKEN,
  SMS_SDKAPPID,
  SMS_SIGN,
  SMS_TEMPLATE_ID,
} = process.env;

module.exports = {
  APP_HOST,
  APP_PORT,
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USER_NAME,
  MYSQL_PASSWORD,
  MYSQL_DATABASE,
  TENCENTCLOUD_SECRETID,
  TENCENTCLOUD_SECRETKEY,
  TENCENTCLOUD_SESSIONTOKEN,
  SMS_SDKAPPID,
  SMS_SIGN,
  SMS_TEMPLATE_ID,
};
